### PR TITLE
Rel 2.0.2

### LINKED ISSUE #74: lxml
Is used in Alex's Beckhoff tagging script

### PR DESCRIPTION
**Pull request by ZLLentz**
Not a huge release, shouldn't be any API breaks.

Primarily to fix the ipython bug that was driving me crazy.

closes #74

### CODE REVIEW

**Comment by teddyrendahl** [comment]
@silkenelson wants the newer version of `bokeh` which for some reason is not being pulled automatically?

Can you try pinning `bokeh` to `1.0.1`?

**Comment by ZLLentz** [comment]
It didn't pick up the new `bokeh` because `conda` decided that `holoviews` was more important... I'll pin it to >=1.0.1
```
$ conda install bokeh=1.0.1
Solving environment: done

## Package Plan ##

  environment location: /reg/neh/home/zlentz/conda/envs/pcds-2.0.2

  added / updated specs: 
    - bokeh=1.0.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bokeh-1.0.1                |           py36_0         5.3 MB
    holoviews-1.10.4           |           py36_0         3.5 MB
    ------------------------------------------------------------
                                           Total:         8.7 MB

The following packages will be UPDATED:

    bokeh:     0.13.0-py36_0 --> 1.0.1-py36_0 

The following packages will be DOWNGRADED:

    holoviews: 1.10.7-py36_0 --> 1.10.4-py36_0
```

**Comment by ZLLentz** [comment]
As an aside, it completely escapes me how conda decides which packages to keep in the case where "latest/latest" is invalid.

**Comment by teddyrendahl** [comment]
Frightening ... I do not understand it either

**Comment by ZLLentz** [comment]
Seems like `holoviews` was the only regression

**Comment by ZLLentz** [comment]
Everything seems ok, I'll tag and install 2.0.2 before the night is over

**Pull request merged**
