### PR TITLE
CI: Travis

### PR DESCRIPTION
**Pull request by ZLLentz**
Runs our package tests with the environment. Check out the travis output!

This works by doing some github checkouts and going around to all the individual module tests.

I'm pleased with how this turned out because I've previously been afraid that small environment changes could break particular projects. This will catch any bug covered by any of the module tests.

### CODE REVIEW

**Comment by teddyrendahl** [comment]
This is awesome! It feels good that all of the battles we have been through making the testing suites standard pays off when something like this is relatively easy to do.

1) This is reasonable enough that it might be interesting in a nightly build where we use `pcds-dev` instead of the tag? (Haven't fully thought through if this works like I think it does) Might catch things sooner than when we go to actually make the release and have an "OH 💩 !" moment
2) Looks like we have to select our repositories we test this way by hand. I am thinking of a way where we assemble this automatically. Maybe have a blacklist instead of a whitelist. This would save us from forgetting to add devices but probably hurt us when the tests require some special setup (a la `lightpath`)

**Comment by ZLLentz** [comment]
1. We can set up a nightly using dev, but it'd take a different route than this one. This uses a particular version's `pcds.yaml` file as the environment, then clones all the repos and checks out the tags to run the tests of this particular release's `pcds.yaml` file. Instead, the dev nightly would run `create_base_env.sh` with `pcds-dev`, `pcds-tag`, `defaults`, and `conda-forge` as the channels, clone all the repos, and skip checking out the tags. So basically a "what if we tried to create a new environment now but on dev". Definitely worth doing. We probably should just make a split in the build matrix and run both tag/dev on PR and nightly for simplicity. Actually, we can do three flavors: `pcds.yaml`, `create_base_env.sh` with `pcds-dev`, and `create_base_env.sh` without `pcds-dev`.
2. The closest thing I can think of to automatically selecting all is doing the equivalent of `conda list | grep pcds-tag`, cloning those repos if they exist in github, and doing `python run_tests.py` if the tests also exist. This adds some complexity but not a huge amount.

Do you think we should do these as part of this PR or separately?

**Comment by teddyrendahl** [comment]
1. Hmm. Might be getting too convoluted... we can discuss
2. That is what I was imagining. Want to try it and see what happens?

**Comment by ZLLentz** [comment]
FYI 2 adds more complication than 1. I'm willing to try both.

**Comment by teddyrendahl** [comment]
😆 I meant that #1 has less clear goals.

**Pull request merged**
