### PR TITLE
REL: pcds-5.7.2

### LINKED ISSUE #280: Add atef unit tests
It's not installed yet, but we should still test them.
Offline these are now hanging on pcds-5.7.0

### LINKED ISSUE #283: Drop the packaging regressive pin
Next env we should be able to drop this pin and restore latest-update status to `black`

### LINKED ISSUE #284: next env fails on sphinx update
I noticed that the weekly build failed

sphinx has released version 7.0.0 but this is not installable with our current specs:

```
 sphinxcontrib-jquery 4.1     pyhd8ed1ab_0 sphinx >=1.8
 docs-versions-menu   0.5.1   pyhd8ed1ab_0 sphinx
 numpydoc             1.5.0   pyhd8ed1ab_0 sphinx >=1.8
 sphinx_rtd_theme     1.2.0   pyha770c72_0 sphinx >=1.6,<7
```

Here are the release notes:
https://www.sphinx-doc.org/en/master/changes.html#release-7-0-0-released-apr-29-2023

We can't update this until sphinx_rtd_theme also updates, after which we would need to evaluate if our docs builds still run with latest. So it may be most prudent to simply remove this off the keep-updated list for now.

### LINKED ISSUE #285: Request: include an IDE
It should be easy to include spyder or jupyterlab via conda and may be helpful at the operator consoles for editing code

VSCode or PyCharm could be installed separately on the console machines themselves

### PR DESCRIPTION
**Pull request by ZLLentz**
Addresses the following:
closes #280 
closes #283 
closes #284 
closes #285

Release notes paste:

PCDS Package Updates
--------------------

|   Package   |  Old  |  New  |                       Release Notes                        |
|:-----------:|:-----:|:-----:|:----------------------------------------------------------:|
|    blark    | 0.5.0 | 0.6.0 |    https://github.com/pcdshub/blark/releases/tag/v0.6.0    |
|    happi    | 2.1.1 | 2.2.0 |    https://github.com/pcdshub/happi/releases/tag/v2.2.0    |
| pcdsdevices | 7.3.0 | 7.4.0 | https://github.com/pcdshub/pcdsdevices/releases/tag/v7.4.0 |
| psdaq-control-minimal | 3.3.19 | 3.3.38 | https://github.com/pcdshub/psdaq-control-minimal/releases/tag/v3.3.38 |

Python Community Core Package Updates
-------------------------------------

|  Package   |  Old  |  New  |
|:----------:|:-----:|:-----:|
| pre-commit | 3.2.2 | 3.3.1 |

Other Python Community Major Updates
------------------------------------

|     Package     |    Old    |   New    |
|:---------------:|:---------:|:--------:|
|      black      |  22.12.0  |  23.3.0  |
| ca-certificates | 2022.12.7 | 2023.5.7 |
|     certifi     | 2022.12.7 | 2023.5.7 |
|  jupyter_client |   7.3.1   |  8.2.0   |
|    packaging    |    21.3   |   23.1   |

Added the Following Packages
----------------------------

- spyder-kernels

Added the Following Dependencies
--------------------------------

- importlib_metadata (required by jupyter_client)
- wurlitzer (required by spyder-kernels)

### CODE REVIEW

**Comment by ZLLentz** [comment]
This found an incompatibility:
```
├─ flask >=2.3.2  is installable and it requires
│  └─ jinja2 >=3.1.2 , which can be installed;
└─ jinja2 3.0.3  is uninstallable because it conflicts with any installable versions previously reported.
```

We have `jinja2=3.0.3` pinned in the conda dependencies outside of the pinned section, which caused me to miss it.
We have `flask` marked as `keep-updated` which completes the conflict loop.

TODO:
- Figure out why the jinja pin exists
- If the pin must exist, move it to pins section and explain why. Then, hold `flask` back.
- If the pin does not need to exist, unpin it

**Comment by ZLLentz** [comment]
Ref https://github.com/pcdshub/pcds-envs/pull/225#issuecomment-1086351294
Querying our current env implies that everything is ok now and I can unpin jinja2
Since jinja2 is a dependency of other projects and was only added to the list for the purposes of the pin, the correct action is to completely remove it from conda-packages

**Comment by klauer** [comment]
It feels off to me to not constrain an important dependency like jinja2 to me - at least from the perspective of creating a reproducible environment. I'd expect to be able to rebuild pcds-5.7.2 in a month (without running any update scripts) and not see a difference.

Am I off-base about that goal of pcds-envs? It seems so

**Comment by ZLLentz** [comment]
The version at a specific tag is constrained fully to a version number + a build number for every single package, so the reproducibility issue isn't a problem.

For "minor update" (x.x.1) builds we hardly update anything if we don't have to, so I suspect in general that the version of jinja2 won't update unless it needs to until we do a  x.1.x full rebuild.

We did pick a small number of packages to fully freeze "forever" (qt stuff, ipython) and I'm happy to add jinja2 to that list if your experience is that version stability there is critical. This might just be my ignorance in allowing it to drift upward.

In this case the env wanted to update it because I added a bunch of "developer tools" to keep-updated and one of them (flask) decided it needed a newer version than our static freeze. So, the static pin blocked the build and I naively removed the static pin since the original justification for it no longer applied.

Anyway, I'm happy to freeze jinja2 again (at the same number or at a specific new one) and downgrade other packages as needed to accommodate this. I'll add a comment to it along the lines of "keep jinja2 stable, can break packages unexpectedly when it updates"

**Comment by klauer** [comment]
You're doing a fantastic job with the packaging, apologies if my question came off implying otherwise. I'm merely trying to clear things up in my own head as to the goals and the direction you're taking it. I'm more than happy to have you in the driver's seat here! 😁 

> Anyway, I'm happy to freeze jinja2 again (at the same number or at a specific new one) and downgrade other packages as needed to accommodate this. I'll add a comment to it along the lines of "keep jinja2 stable, can break packages unexpectedly when it updates"

There were things in the past that were problematic with Jinja (_years_ ago). There's nothing recent that warrants concern, I'd say. That said, it is a fundamental package for a number of our libraries. 

> Does this action make sense? I don't mean to make you feel off-base about the goals here, I think our goals are aligned and that I'm a human that makes mistakes.

I don't think it's necessarily a mistake. Your explanation above clears things up. Thanks!

**Comment by ZLLentz** [comment]
> There were things in the past that were problematic with Jinja (years ago). There's nothing recent that warrants concern, I'd say. That said, it is a fundamental package for a number of our libraries.

OK, in that case what I want to do is let it be for now, continue the "update things minimally whenever we can get away with it" and trust the test suite's power to alert us to a breaking change.

Maybe I was too heavy-handed in marking things as "keep-updated" though, here's the current list that we could consider paring down: https://github.com/pcdshub/pcds-envs/blob/88d1592cd1686169d9b50abe923dc523a094b706/envs/pcds/keep-updated.txt

**Comment by ZLLentz** [comment]
I removed a few items from the keep updated list and tried to justify my choices in-file
Once I've successfully ran the update scripts again I'll push here and hopefully everything passes?

If everything passes I'll experiment a bit with doing a release via stealing the output yaml file from gha rather than doing the full build locally (just doing the install-into-conda step locally to run local tests)

**Comment by ZLLentz** [comment]
One remaining issue:
Instead of removing the xraydb/sqlalchemy conflict pin, I reversed it, but this breaks some envs because `pcdsdevices` itself has this pin built-in on the conda recipe side.
I'm going to remove the pin here instead of reversing it and trust that other packages that had this pin can be tested and have the pin removed in the future without the env needing to keep track of it.

**Comment by ZLLentz** [comment]
OK, yeah, not in the conda recipe but in the `requirements.txt` file, both pcdsdevices and pcdscalc enforce the xraydb/sqlalchemy pin which breaks on `pip check` in some envs

**Comment by ZLLentz** [comment]
If I did this right, all the tests should pass (except for py311, which still should not be able to build) and then the "full" builds should fail the pip check (since they likely update xraydb) even though all the tests pass, which would demonstrate that it'd be safe to remove the requirements.txt pins.

The minimal update env (the one I plan to deploy) should pass everything because it won't try to update xraydb at all.

**Comment by ZLLentz** [comment]
Ok, I'm pretty satisfied with this. Tomorrow I'll check what the gha yaml looks like and maybe feed it back in to this PR or onto a separate one.

**Comment by ZLLentz** [comment]
I think I'm just going to keep using this PR for the env release to keep all the updates in one place.

**Comment by ZLLentz** [comment]
The offline tests pass and this looks pretty good too
Tomorrow is deploy day

**Review by klauer — APPROVED** [review]

**Comment by ZLLentz** [comment]
Hmmm it looks like lightpath failed all retries in the last run from last night, sometimes with a segfault and sometimes with the following snippit. I'll give it the good ol' rerun just to be sure.
```
============================= test session starts ==============================
platform linux -- Python 3.9.15, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
PyQt5 5.12.3 -- Qt runtime 5.12.9 -- Qt compiled 5.12.9
rootdir: /home/runner/work/pcds-envs/pcds-envs/scripts/tests/lightpath
plugins: benchmark-4.0.0, aiohttp-0.3.0, asyncio-0.21.0, anyio-3.6.1, timeout-2.1.0, repeat-0.9.1, xdist-3.2.1, qt-4.2.0
asyncio: mode=strict
collected 34 items

lightpath/tests/test_cli.py ..                                           [  5%]
lightpath/tests/test_controller.py .........                             [ 32%]
lightpath/tests/test_gui.py ....F.                                       [ 50%]
lightpath/tests/test_path.py ...............                             [ 94%]
lightpath/tests/test_widgets.py ..                                       [100%]

=================================== FAILURES ===================================
________________________________ test_filtering ________________________________

lightapp = <lightpath.ui.gui.LightApp object at 0x7f3eccdf4310>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f3ecd0d20a0>

    def test_filtering(lightapp: LightApp, monkeypatch):
        lightapp.destination_combo.setCurrentIndex(4)  # set current to MEC
        # Create mock functions
        for row in lightapp.rows:
            monkeypatch.setattr(row[0], 'setHidden', Mock())
        # Initialize properly with nothing hidden
        lightapp.filter()
        for row in lightapp.rows:
            row[0].setHidden.assert_called_with(False)
        # Insert at least one device then hide
        device_row = lightapp.rows[2][0]
        device_row.device.insert()
        lightapp.remove_check.setChecked(False)
        # Reset mock
        for row in lightapp.rows:
            row[0].setHidden.reset_mock()
        lightapp.filter()
        for row in lightapp.rows:
            if row[0].device.get_lightpath_state().removed:
>               row[0].setHidden.assert_called_with(True)

lightpath/tests/test_gui.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Mock id='139907702206272'>, args = (True,), kwargs = {}
expected = call(True), actual = call(False)
_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x7f3ecccdde50>
cause = None

    def assert_called_with(self, /, *args, **kwargs):
        """assert that the last call was made with the specified arguments.
    
        Raises an AssertionError if the args and keyword args passed in are
        different to the last call to the mock."""
        if self.call_args is None:
            expected = self._format_mock_call_signature(args, kwargs)
            actual = 'not called.'
            error_message = ('expected call not found.\nExpected: %s\nActual: %s'
                    % (expected, actual))
            raise AssertionError(error_message)
    
        def _error_message():
            msg = self._format_mock_failure_message(args, kwargs)
            return msg
        expected = self._call_matcher(_Call((args, kwargs), two=True))
        actual = self._call_matcher(self.call_args)
        if actual != expected:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: expected call not found.
E           Expected: mock(True)
E           Actual: mock(False)

/home/runner/miniconda/envs/pcds-test/lib/python3.9/unittest/mock.py:907: AssertionError
```

**Comment by ZLLentz** [comment]
```
All package tests passed!
The following packages had race conditions, but passed at least once:
tests/lightpath

Extra tests passed

No broken requirements found.
```

**Review by tangkong — APPROVED** [review]
Man I missed all this discussion when it happened :( 

I really need to loop back on those lightpath tests.  They really give us trouble at every turn

**Comment by ZLLentz** [comment]
ok I'm gonna start running the deploy scripts now, lets gooo

**Pull request merged**
