### PR TITLE
ENH: pcds-4.2.0

### PR DESCRIPTION
**Pull request by ZLLentz**
# Hello, Python 3.9!

This is an update that incorporates a jump to Python 3.9 with a host of local package updates. We do not expect this to break any code but it is worth acknowledging the new version and being aware that the Python 3.9 features are now available.

https://docs.python.org/3/whatsnew/3.7.html
https://docs.python.org/3/whatsnew/3.8.html
https://docs.python.org/3/whatsnew/3.9.html

In the future we plan to stay up-to-date with the latest officially released Python versions.

## ECS Packages:
Plenty of feature and bugfix releases from within our team!
There are a few maintenance/packaging releases that have been omitted from this list.
|  Package | Old | New | Release Notes |
| - | - | - | - |
| blark | N/A | 0.1.6 | https://github.com/klauer/blark/releases/tag/v0.1.5 |
| hutch-python | 1.11.1 | 1.11.2 | https://github.com/pcdshub/hutch-python/releases/tag/v1.11.2 |
| lucid | 0.8.0 | 0.9.0 | https://github.com/pcdshub/lucid/releases/tag/v0.9.0 |
| pcdsdevices | 4.6.0 | 4.7.1 | https://github.com/pcdshub/pcdsdevices/releases/tag/v4.7.0 https://github.com/pcdshub/pcdsdevices/releases/tag/v4.7.1 |
| pcdsutils | 0.4.3 | 0.5.0 | https://github.com/pcdshub/pcdsutils/releases/tag/v0.5.0 |
| pytmc | 2.9.1 | 2.10.0 | https://github.com/pcdshub/pytmc/releases/tag/v2.10.0 |
| typhos | 1.2.0 | 2.0.0 | https://github.com/pcdshub/typhos/releases/tag/v2.0.0 |

## LCLS DAQ Packages:
We're using a simplified psdaq control interface now with fewer dependencies and several improvements. This means that packages like psana and the related tools are no longer part of the pcds dependencies.
|  Package | Old | New | 
| - | - | - | 
| psdaq-control-minimal | 3.3.14 | 3.3.19 |
| psana | 3.3.14 | removed |

## SLAC Packages:
There is a minor release over at PyDM to allow users to opt-out of an on-close pop-up, and it also brings in a bunch of miscellaneous undocumented changes to other PyDM internals.
|  Package | Old | New | 
| - | - | - | 
| pydm | 1.11.0 | 1.11.1 |

## Lab Community Packages:
Check out the bluesky feature release! For most users, this just means some fixes and maintenance improvements.
| Package | Old | New | 
| - | - | - | 
| bluesky | 1.6.7 | 1.7.0 |

## Python Community Packages:
I didn't delve into the details on any of these, but here are some notable general Python community libraries that have been updated or added to the environment.
| Package | Old | New | 
| - | - | - | 
| ipython | 7.25.0 | 7.26.0 |
| lark-parser | N/A | 0.11.3 |
| numpy | 1.21.0  | 1.21.1 |
| pandas | 1.3.0 | 1.3.1 |
| python | 3.8.10 | 3.9.6 |
| scipy | 1.7.0 | 1.7.1 |
| sphinx | 4.1.0 | 4.1.2 |
| xarray | 0.18.2 | 0.19.0 |

## Miscellaneous
This update also adds a test suite for python 3.10, which is not released yet. This is so that when python 3.10 is released we can start testing against it right away.

### CODE REVIEW

**Comment by ZLLentz** [comment]
This will be re-run with an updated version of `blark`, but it shouldn't change the outcome at all.

**Comment by ZLLentz** [comment]
Before marking as ready for review, I am going to do some hands-on tests with lucid and pmps-ui to make sure there aren't any obvious things going wrong. This is because we have updates to both pydm and to python itself.

**Comment by ZLLentz** [comment]
- pmps-ui was not running properly due to the update to pydm, but we've resolved the reason and have a patch.
- typhos screens for state devices do not have the correct templates loaded, there is likely either a typhos bug or a packaging mistake with pcdsdevices, investigating further

**Comment by ZLLentz** [comment]
Ahh my mistake in pcdsdevices, I thought I checked this well enough
```
In [1]: from typhos.utils import DISPLAY_PATHS

In [2]: DISPLAY_PATHS
Out[2]:
[PosixPath('/cds/home/z/zlentz'),
 PosixPath('/cds/home/z/zlentz/miniconda3/envs/pcds-4.2.0/lib/python3.9/site-packages/pcdsdevices/ui'),
 PosixPath('/cds/home/z/zlentz/miniconda3/envs/pcds-4.2.0/lib/python3.9/site-packages/typhos/ui/core'),
 PosixPath('/cds/home/z/zlentz/miniconda3/envs/pcds-4.2.0/lib/python3.9/site-packages/typhos/ui/devices')]

In [3]: ls /cds/home/z/zlentz/miniconda3/envs/pcds-4.2.0/lib/python3.9/site-packages/pcdsdevices/ui
__init__.py  __pycache__/

In [4]:
```

**Comment by ZLLentz** [comment]
This will be rebuilt with pcdsdevices=4.7.1 tomorrow

**Comment by ZLLentz** [comment]
Offline testing shows that this issue is resolved. The state positioner and attenuator calculator screens now display as intended.

**Review by klauer — APPROVED** [review]
My emojis and words will not do this justice - but this is a significant release that I'm excited for. Extra marks for the extremely nice changelist. (I still think you should bring it to confluence, as well, to increase the chances that others read it!)

**Comment by ZLLentz** [comment]
I'll make a confluence page for pcds-conda release notes and populate it during the all-hands. Hopefully confluence can show markdown so I don't have to redo the tables.

**Comment by ZLLentz** [comment]
I will tag now but deploy this next week out of an abundance of caution for the last few shifts of the run

**Pull request merged**
