### PR TITLE
MNT: bump epics-pypdb to 0.1.5

### PR DESCRIPTION
**Pull request by klauer**
Pending https://github.com/conda-forge/epics-pypdb-feedstock/pull/2

### CODE REVIEW

**Comment by ZLLentz** [comment]
Is the intention to tag a release after this? You've manually edited the generated environment description file.

**Comment by klauer** [comment]
That was stupid of me. Closing.

**Comment by ZLLentz** [comment]
Should we bump the depending package's conda requirement instead? Or is this to be used directly and we need to add `epics-pypdb >=0.1.5` to the `conda-package.txt` file?

**Comment by klauer** [comment]
I think a pytmc pin of epics-pypdb may be the right course of action...

**Comment by ZLLentz** [comment]
Ok, that seems reasonable. We probably need to do that anyway to make it clear what is needed in `pytmc`

**Pull request closed without merging**
