### PR TITLE
ENH: updated pcds to 4.1.3

### PR DESCRIPTION
**Pull request by ZLLentz**
PCDS package updates:
|  Package | Old | New |
| - | - | - |
| elog | 1.0.2 | 1.2.0 |
| nabs | 1.1.1 | 1.1.2 |
| pcdscalc | 0.2.0 | 0.3.0 |
| pytmc | 2.9.0 | 2.9.1 |

Lab community package notable updates:
N/A, misc minor releases

Python community package notable updates:
N/A, misc minor releases

### CODE REVIEW

**Comment by ZLLentz** [comment]
@klauer the transfocate tests failed- should I not have tagged `v0.5.1`?

**Comment by ZLLentz** [comment]
I have decided to hold transfocate back because Ken is out today and I am out tomorrow

**Comment by klauer** [comment]
Can we mark it as xfail for now?  It's OK if not - dev install is in place regardless of pcds-envs inclusion.
Tests need updating 🧪

**Comment by ZLLentz** [comment]
Yes exactly, I figured you were running out of dev anyway and it's easier to just keep the "all tests must pass" policy

**Pull request merged**
