### PR TITLE
MNT: build using conda-forge as priority, no defaults, no free

### LINKED ISSUE #159: Python 3.8 Conflict List
`lightpath` does not have any noarch builds with open dependencies. I'm doing a first attempt at resolving this here: https://github.com/pcdshub/lightpath/pull/119

`hutch-python` depends on `lightpath` and also fails to install on 3.8, probably because of `lightpath`.

`pytest` has a <4 pin that prevents us from doing python>=3.8. That is also being tracked at #139

### PR DESCRIPTION
**Pull request by ZLLentz**
This more closely matches the shared travis configs for the various packages, should build faster and more reliably.

The defaults/free channel existed in the configuration only to support the old version of mysqlclient.
"Free" is the packages that were removed from defaults to decrease the search space and make conda run faster.
"Defaults" are the anaconda.org packages.

This means we'll be leaning heavily on the clean conda-forge recipes.

Incidentally closes #159

### CODE REVIEW

**Comment by ZLLentz** [comment]
The build immediately fails because the existing tagged env requires the channels I've removed here. I'm going to generate a 3.5.1 environment with the current specifications but this new channel loadout to see if it would work at all.

**Comment by ZLLentz** [comment]
This new environment seems to be solving/building well offline. I'll push a new yaml to see how it works out at large.

**Comment by ZLLentz** [comment]
stopped by `pyca` packaging issue:
```
ImportError: libca.so.7.0.3.99.4: cannot open shared object file: No such file or directory
```
Can probably work around this without too much trouble

**Comment by klauer** [comment]
Were you thinking of something like using pyepics + `PYEPICS_LIBCA` or conda-forge `epics-base` for its build?

**Comment by ZLLentz** [comment]
Now that you've asked that question I realize that I'm not quite sure what I'm doing here
For some reason, pyca is linked agains epicscorelibs 7.0.3.99.4 but this environment has 7.0.3.99.1

**Comment by ZLLentz** [comment]
Now that this is basically working, I see a huge speedup on failed builds and a small speedup on successful builds. The failed builds are no longer hitting my 10m/20m timeouts, whereas previously these would take ~1hr to run on my desktop machine.

**Comment by klauer** [comment]
I clearly didn't know what I was asking, and it looks like you figured it out to great effect - just pinning to `epicscorelibs=7.0.3.99.4.0` was the solution. 👏

**Comment by ZLLentz** [comment]
Unit tests pass on python 3.8 now! Very close to being "caught up"

**Review by klauer — APPROVED** [review]

**Pull request merged**
