### PR TITLE
CI: add very ambitious 3.9 builds

### LINKED ISSUE #87: Python 3.7 Conflict List
Did a quick check, using the following methodology:
1. Try to make the 3.7 env
2. Record package chain in conflict
3. Remove all elements in conflict chain from packages file
4. Repeat until the environment is allowed to build

Python 3.7 conflict list:
- `elog`
- `hxrsnd` -> `pswalker`
- `hutch-python` -> `elog`
- `pcdsdaq`
- `pmgr`
- `transfocate`

These should all be trivial except for `pmgr` which uses a custom `pyqt` build.

### PR DESCRIPTION
**Pull request by ZLLentz**
These should theoretically be possible now?
I'm running this to see if I need to refresh my py3.7 incompatibility list and so we'll know when it's time to upgrade the whole environment.

There may be a follow-up PR to bump the primary build from 3.6

Closes #87

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm examining the reason for the failure offline and adding a hopefully helpful travis stage for showing what failed. It's important to keep it within exactly one travis job because otherwise it will eat up our 5 concurrent build allocation.

**Comment by klauer** [comment]
Is the environment solve taking > 10 minutes? `The command "timeout 10m ./update_env.sh pcds-test pcds 3.8 && popd" exited with 124.` 😬

**Comment by ZLLentz** [comment]
The environment solve takes >10m largely because it fails, unfortunately. I have one terminal running with the built-in conda conflict analyzer and a second terminal running the conda_debug.sh script. I have a vim open adding conda_debug.sh to the travis config to see if it's helpful or not.

**Comment by ZLLentz** [comment]
I am not amused

The problem the whole time was that I forgot to make a tag... oops

**Comment by ZLLentz** [comment]
Another victory for conda_debug.sh, which took more than an hour to run but gave human-readable output:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pmgr[version='>=1.1.3'] -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.7
```

**Comment by ZLLentz** [comment]
Next theory, which I will see the results of in the morning, is that the next env build strategy (take newest env, update it) is very slow for changing the python version. Switching strategy to the slow but less slow build from scratch, removing time limit from these builds and we'll check on it tomorrow.

**Comment by ZLLentz** [comment]
The 3.7 build worked, some CI issue prevents the test from running. I'll try a fix.

3.8 and 3.9 builds did not work, so I'll run the debugger again on 3.8 to gain data.

**Comment by klauer** [comment]
3.7 is a good step forward, at least! I was overly hopeful about 3.9 for reasons not grounded in reality...

**Comment by ZLLentz** [comment]
3.7 unit tests pass now, the debugger is still running and has identified the following incompatibilities for 3.8 so far
- hutch-python (with an empty conflicts output??)
- lightpath (with a clear conflict output)

I will now investigate lightpath's recipe

**Comment by ZLLentz** [comment]
Another thing to solve for 3.8: our pytest<4 pin only works up to 3.7. But I've been wanting to nuke that pin for a long time.
I'm going to push a commit that puts a time limit on the remaining failed solves without time limits to cut off the travis usage early, then call this PR done. I will have a follow-up PR investigating pytest<4.

**Review by klauer — APPROVED** [review]
All looks good on my end. Glad to see the progress here, and forward-looking builds. 👍

**Pull request merged**
