### PR TITLE
Rel 2.1.0

### PR DESCRIPTION
**Pull request by ZLLentz**
- Remove pre-1.6 pin on `pydm`
- Get latest everything

Does anyone remember why we were pinning `pydm` to pre-1.6? This is why the environments weren't being constructed with the latest `typhon`.

Let me know if see something odd in the version changes. The only thing immediately strange-looking to me is that we now have every package remarkably alphabetized in the yaml file, probably from a `conda` update.

### CODE REVIEW

**Comment by klauer** [comment]
I don't see anything particularly strange, but admittedly version numbers aren't something I normally pay too much attention to... @teddyrendahl?

**Comment by ZLLentz** [comment]
```
__________________________ test_typhon_panel_sorting ___________________________
qapp = <pydm.application.PyDMApplication object at 0x7fe558676798>
client = <happi.client.Client object at 0x7fe5547d3940>
qtbot = <pytestqt.qtbot.QtBot object at 0x7fe53853d908>
    @show_widget
    def test_typhon_panel_sorting(qapp, client, qtbot):
        panel = TyphonSignalPanel()
        qtbot.addWidget(panel)
        # Sort by name
        panel.sortBy = panel.SignalOrder.byName
        panel.channel = 'happi://test_motor'
        qapp.establish_widget_connections(panel)
        sorted_names = sorted(panel.devices[0].component_names)
        sig_layout = panel.layout().layout()
        assert list(panel.layout().signals.keys()) == sorted_names
        # Sort by kind
        panel.sortBy = panel.SignalOrder.byKind
        key_order = list(panel.layout().signals.keys())
        assert key_order[0] == 'readback'
>       assert key_order[-1] == 'unused'
E       AssertionError: assert 'setpoint' == 'unused'
E         - setpoint
E         + unused
tests/test_signal.py:145: AssertionError
```

**Comment by ZLLentz** [comment]
could be related to outdated ophyd version

**Comment by ZLLentz** [comment]
`typhon` passes now, but we need a new `pcdsdevices` tag and the `hxrsnd` tests are dead in the water

**Comment by teddyrendahl** [comment]
I believe we pinned because `pydm=1.6.0` as there were quite a rapidly released versions afterwards and we wanted to wait for it to settle?

```
v1.6.0
v1.6.1
v1.6.2
v1.6.3
v1.6.4
v1.6.5
```

**Comment by ZLLentz** [comment]
It has turned green

**Comment by ZLLentz** [comment]
@teddyrendahl time to merge and deploy?

**Pull request merged**
