### PR TITLE
ENH: pcds-5.1.0

### PR DESCRIPTION
**Pull request by ZLLentz**
Prospective release
Unclear if we should do this as-is or wait for typhos, pydm, and whatrecord tags
I'm out next week so I figured it was time to press the button
Hopefully the unit tests pass

Generated release notes:

Added the Following Packages
----------------------------

- aiosignal
- aom
- atlassian-python-api
- c-blosc2
- fonttools
- freeglut
- frozenlist
- libdrm
- libglu
- libpciaccess
- libva
- libvpx
- mesalib
- munkres
- python-tzdata
- pytz-deprecation-shim
- qrcode
- setuptools-scm
- svt-av1
- x265
- xorg-fixesproto
- xorg-inputproto
- xorg-libxfixes
- xorg-libxi

Removed the Following Packages
------------------------------

- inflection
- sleef

PCDS Package Updates
--------------------

|   Package    |  Old   |  New   |                        Release_Notes                         |
|:------------:|:------:|:------:|:------------------------------------------------------------:|
|    happi     | 1.10.0 | 1.10.1 |    https://github.com/pcdshub/happi/releases/tag/v1.10.1     |
| hutch-python | 1.12.0 | 1.13.0 | https://github.com/pcdshub/hutch-python/releases/tag/v1.13.0 |
| pcdsdevices  | 4.8.0  | 5.0.0  |  https://github.com/pcdshub/pcdsdevices/releases/tag/v5.0.0  |
|  pcdsutils   | 0.5.0  | 0.6.0  |   https://github.com/pcdshub/pcdsutils/releases/tag/v0.6.0   |
| pcdswidgets  | 0.5.1  | 0.6.0  |  https://github.com/pcdshub/pcdswidgets/releases/tag/v0.6.0  |
|    pytmc     | 2.10.0 | 2.11.0 |    https://github.com/pcdshub/pytmc/releases/tag/v2.11.0     |
|    typhos    | 2.0.0  | 2.1.0  |    https://github.com/pcdshub/typhos/releases/tag/v2.1.0     |
|  whatrecord  | 0.1.3  | 0.2.1  |  https://github.com/pcdshub/whatrecord/releases/tag/v0.2.1   |

Lab Community Package Updates
-----------------------------

|   Package    |  Old  |  New  |
|:------------:|:-----:|:-----:|
|   bluesky    | 1.8.0 | 1.8.1 |
| bluesky-live | 0.0.7 | 0.0.8 |
|  databroker  | 1.2.3 | 1.2.4 |
|    ophyd     | 1.6.2 | 1.6.3 |

Python Community Core Package Updates
-------------------------------------

| Package |  Old   |  New   |
|:-------:|:------:|:------:|
|  flake8 | 3.9.2  | 4.0.1  |
| ipython | 7.28.0 | 7.29.0 |
|  sphinx | 4.2.0  | 4.3.0  |
|  xarray | 0.19.0 | 0.20.1 |

Other Python Community Major Updates
------------------------------------

|      Package      |   Old    |  New   |
|:-----------------:|:--------:|:------:|
|    argon2-cffi    |  20.1.0  | 21.1.0 |
|   async-timeout   |  3.0.1   | 4.0.1  |
|      cfitsio      |  3.470   | 4.0.0  |
|      coverage     |   5.5    | 6.1.2  |
|    cryptography   |  3.4.7   | 35.0.0 |
|     decorator     |  4.4.2   | 5.1.0  |
|      harfbuzz     |  2.9.1   | 3.1.1  |
|   humanfriendly   |   9.2    |  10.0  |
|       jasper      | 1.900.1  | 2.0.33 |
|        lerc       |  2.2.1   |  3.0   |
|     pyopenssl     |  20.0.1  | 21.0.0 |
|     pyparsing     |  2.4.7   | 3.0.6  |
|   pytest-timeout  |  1.4.2   | 2.0.1  |
|       pyyaml      |  5.4.1   |  6.0   |
|     setuptools    |  58.0.4  | 59.1.1 |
| typing-extensions | 3.10.0.2 | 4.0.0  |
| typing_extensions | 3.10.0.2 | 4.0.0  |
|       tzdata      |  2021b   | 2021e  |
|      tzlocal      |   3.0    |  4.1   |

### CODE REVIEW

**Comment by ZLLentz** [comment]
There are some frustrating interactions with `pyca`, unspecified run dependencies, and `epicscorelibs`.
Building the environment from the conda-packages.txt file works great because I specify the correct build string to download, but the env.yaml file drops this information, so the environment build from the env.yaml spec picks up the wrong pydm and fails.

I want to think a bit about whether or not I want to fix the `epicscorelibs` packaging today/tomorrow and if there's a way to record the specific build strings used in the environment. It's possible that rebuilds have occasionally subtly changed our environments in the past with no git/yaml record and this makes me uncomfortable.

**Comment by ZLLentz** [comment]
Update: apparently, I explicitly ask for no build strings in the staging script. I've changed my opinion on this and am revising accordingly.

**Comment by ZLLentz** [comment]
the "dev" build fails on `typhos`, the tag builds all pass with the current setup

**Comment by klauer** [comment]
Well, TIL: https://sleef.org/ (where did that dep come in, and why did it go?)

Not much to say on the env release itself; nothing jumped out as suspicious.

**Comment by ZLLentz** [comment]
That struck me as odd as well- I'm not sure if there's a quick and easy way to track why a particular dependency was dropped. There's probably a script we could write if it becomes important.

**Comment by ZLLentz** [comment]
I'll do the rest of this tomorrow morning (merge, tag, deploy)

**Comment by ZLLentz** [comment]
I'm having some trouble getting the typhos update into here (see the master branch failures).
Those two tests fail in the big environment (on master, not in tag) but are skipped in the typhos travis so the tests there pass happily. I see no paths by which those tests could ever be skipped so I am extremely confused.

In my local tests, those two tests fail, so I should be able to debug it, but getting them to run at all on the CI is an important step.

pcds-envs failure: https://app.travis-ci.com/github/pcdshub/pcds-envs/jobs/548807304#L7874-L7875
typhos skip with "could not impo...": https://app.travis-ci.com/github/pcdshub/typhos/jobs/548815993#L2874-L2875
typhos skip summary referencing a _different_ test: https://app.travis-ci.com/github/pcdshub/typhos/jobs/548815993#L3054-L3057

I'll do the "install pcdsdevices in typhos tests" thing as a check but the test output seems to indicate it must be unrelated, unless this is some sort of pytest bug.

**Comment by ZLLentz** [comment]
I'm going to deploy this as-is because it's done and expect to want to do a follow-up after thanksgiving

**Comment by ZLLentz** [comment]
Ok, funny story. One of the packages in our tag (nbclient=0.5.8) was yanked from conda and pypi within the last 12 hours. So we're going to need to make some post-adjustments here.

**Pull request merged**
