### PR TITLE
ENH: pcds-3.3.0 environment release

### PR DESCRIPTION
**Pull request by ZLLentz**
- Lots of new tags
- This is definitely broken and I will need to go around to all the "less-used" repos to fix, especially those that rely on `ophyd` but are not part of `pcdsdevices`

(I still would like to merge these small repos into `pcdsdevices` to make the stack easier to maintain and update uniformly.)

### CODE REVIEW

**Comment by ZLLentz** [comment]
List of failing packages with my first-pass diagnosis:
- hutch-python: (???) all tests pass, with tons of happi warnings, and then return exit code 124
- hxrsnd: `ophyd` api incompatibility: `RuntimeError: The success state of a status object cannot be changed by setting its `success` attribute directly. Call `set_finished()` or `set_exception(exc)`.`
- lightpath: `typhos` api incompatibility: `ModuleNotFoundError: No module named 'typhos.signal'`
- pcdsdaq: things are timing out, probably my bad or an ophyd incompatibility
- pswalker: `ophyd` api incompatibility: `RuntimeError: The success state of a status object cannot be changed by setting its `success` attribute directly. Call `set_finished()` or `set_exception(exc)`.`
- pyca: `epics` version incompatibility: `ImportError: libca.so.7.0.3.99.1: cannot open shared object file: No such file or directory`
- transfocate: probably the same `ophyd` status timing issue solved in `pcdsdevices`. This also checks .value a lot, creating a ton of log spam.
- typhos: need to add `pytest-benchmark` to the environment: `run_tests.py: error: unrecognized arguments: --benchmark-skip`

**Comment by ZLLentz** [comment]
Remaining issues:
hutch-python: All tests pass, with tons of happi warnings, and then return exit code 124. I am setting up a local environment to try to reproduce. I'll probably fix the warnings while I'm here.
pyca: epics version compatibility still broken, I'm still ignoring this for now
typhos: missing line_profiler, I will add it.

Also the build doesn't have the qtdesigner path set up:
```
E       AssertionError: assert 'etc/typhos' in '/home/travis/miniconda/envs/pcds-test/etc/pydm:'
E        +  where '/home/travis/miniconda/envs/pcds-test/etc/pydm:' = <function getenv at 0x7fbf31aa47b8>('PYQTDESIGNERPATH', '')
E        +    where <function getenv at 0x7fbf31aa47b8> = os.getenv
```
@hhslepicka is this the same PYQTDESIGNERPATH on conda-forge thing from way back?

**Comment by hhslepicka** [comment]
Typhos at conda-forge is missing the build script that sets the env var. I will put up a PR for that.

**Comment by hhslepicka** [comment]
Conda-forge PR is up... https://github.com/conda-forge/typhos-feedstock/pull/4
As soon as tests are passing I will merge it... after merging it will take about 15-30 minutes for the new package to be available.

**Comment by ZLLentz** [comment]
Thank you very much Hugo! I'm still debugging the other weird things here

**Comment by ZLLentz** [comment]
This environment is GREEN

**Comment by ZLLentz** [comment]
I will merge this now and call it a week. If none of the crons fail over the weekend this can be tagged and deployed on Monday.

**Pull request merged**
