### PR TITLE
ENH: updated pcds to 5.2.2

### PR DESCRIPTION
**Pull request by ZLLentz**
Goal: pick up pydm tag, hope that nothing breaks

SLAC Package Updates
--------------------

| Package |  Old   |  New   |                    Release Notes                     |
|:-------:|:------:|:------:|:----------------------------------------------------:|
|   pydm  | 1.12.0 | 1.13.0 | https://github.com/slaclab/pydm/releases/tag/v1.13.0 |

Other Python Community Major Updates
------------------------------------

|       Package        |  Old   |  New  |
|:--------------------:|:------:|:-----:|
|       humanize       | 3.14.0 | 4.0.0 |
|    python-slugify    | 5.0.2  | 6.0.1 |
| cyclonedx-python-lib | 0.12.3 | 1.3.0 |
|         lz4          | 3.1.10 | 4.0.0 |
|      pip-audit       | 1.1.2  | 2.0.0 |

### CODE REVIEW

**Comment by ZLLentz** [comment]
Seems like everything passed

**Comment by ZLLentz** [comment]
Reminder to self: post issues in various places relating to #203 #204

**Review by klauer — APPROVED** [review]
All LGTM; minor but important update.

**Review by tangkong — APPROVED** [review]
LGTM.  TIL what unicode slugs are

**Comment by klauer** [comment]
@tangkong that's one of my favorite things about new env releases (and all the work Zach has done to make such nice release notes). There's something almost every time to learn about a package, or dependency structure, or other random things like... unicode slugs. 😁

**Pull request merged**
