### PR TITLE
ENH: updated pcds to 5.2.0

### PR DESCRIPTION
**Pull request by ZLLentz**
Auto-generated environment diff:

Added the Following Dependencies
--------------------------------

- alembic (required by tiled)
- argon2-cffi-bindings (required by argon2-cffi, which is used in bluesky, bluesky-live, ipython, jupyter, tiled, xarray)
- asttokens (required by stack-data, stack_data, which are used in ipython)
- executing (required by stack-data, stack_data, which are used in ipython)
- flit-core (required by argon2-cffi, which is used in bluesky, bluesky-live, ipython, jupyter, tiled, xarray)
- libimagequant (required by pillow, which is used in bluesky-live, hutch-python, ipython, ophyd, scikit-image, scikit-learn, suitcase-tiff, tiled, xarray)
- libllvm13 (required by libclang)
- libnsl (required by python)
- mako (required by alembic, which is used in tiled)
- pure_eval (required by stack_data, which is used in ipython)
- qtconsole-base (required by qtconsole, which is used in ipython, jupyter, typhos)
- stack_data (required by ipython)
- ukkonen (required by identify, which is used in pre-commit)
- unicodedata2 (required by charset-normalizer, fonttools, which are used in bluesky, bluesky-live, doctr, hutch-python, ipython, ophyd, pcdsutils, pydm, scikit-image, scikit-learn, sphinx, suitcase-tiff, tiled, whatrecord, xarray)

Removed the Following Packages
------------------------------

- editdistance-s
- glib
- glib-tools
- libllvm11
- mesalib
- mock
- monotonic
- more-itertools
- olefile
- regex
- requirements-parser

PCDS Package Updates
--------------------

|   Package    |  Old   |  New   |                        Release_Notes                         |
|:------------:|:------:|:------:|:------------------------------------------------------------:|
|    happi     | 1.10.1 | 1.11.0 |    https://github.com/pcdshub/happi/releases/tag/v1.11.0     |
| hutch-python | 1.13.0 | 1.13.1 | https://github.com/pcdshub/hutch-python/releases/tag/v1.13.1 |
|     nabs     | 1.1.3  | 1.2.0  |     https://github.com/pcdshub/nabs/releases/tag/v1.2.0      |
| pcdsdevices  | 5.0.2  | 5.1.0  |  https://github.com/pcdshub/pcdsdevices/releases/tag/v5.1.0  |
|  pcdsutils   | 0.6.0  | 0.7.0  |   https://github.com/pcdshub/pcdsutils/releases/tag/v0.7.0   |
| transfocate  | 0.5.2  | 0.5.5  |  https://github.com/pcdshub/transfocate/releases/tag/v0.5.5  |
|    typhos    | 2.2.0  | 2.2.1  |    https://github.com/pcdshub/typhos/releases/tag/v2.2.1     |
|  whatrecord  | 0.2.1  | 0.2.5  |  https://github.com/pcdshub/whatrecord/releases/tag/v0.2.5   |

SLAC Package Updates
--------------------

| Package |  Old   |  New   |
|:-------:|:------:|:------:|
|   pydm  | 1.11.1 | 1.12.0 |

Lab Community Package Updates
-----------------------------

|  Package   |   Old    |   New    |
|:----------:|:--------:|:--------:|
|  bluesky   |  1.8.1   |  1.8.2   |
| databroker | 2.0.0a18 | 2.0.0a20 |
|   tiled    | 0.1.0a45 | 0.1.0a50 |

Python Community Core Package Updates
-------------------------------------

|  Package   |  Old   |  New   |
|:----------:|:------:|:------:|
|  ipython   | 7.30.1 | 8.0.1  |
|   numpy    | 1.21.4 | 1.22.2 |
|   pandas   | 1.3.4  | 1.4.0  |
| pre-commit | 2.16.0 | 2.17.0 |
|   pytest   | 6.2.5  | 7.0.0  |
|   scipy    | 1.7.3  | 1.8.0  |
|   xarray   | 0.20.1 | 0.21.1 |

Other Python Community Major Updates
------------------------------------

|       Package       |         Old         |         New         |
|:-------------------:|:-------------------:|:-------------------:|
|        black        |       21.11b1       |        22.1.0       |
|      cachetools     |        4.2.4        |        5.0.0        |
| conda-forge-pinning | 2021.12.03.08.21.30 | 2022.02.08.09.38.24 |
|         dask        |      2021.11.2      |       2022.1.1      |
|      dask-core      |      2021.11.2      |       2022.1.1      |
|     distributed     |      2021.11.2      |       2022.1.1      |
|        fsspec       |      2021.11.1      |       2022.1.0      |
|         icu         |         68.2        |         69.1        |
|        jinja2       |        2.11.3       |        3.0.3        |
|         jpeg        |          9d         |          9e         |
|       libclang      |        11.1.0       |        13.0.1       |
|        libpq        |         13.5        |         14.1        |
|      markupsafe     |        1.1.1        |        2.0.1        |
|      multidict      |        5.2.0        |        6.0.2        |
|        pillow       |        8.4.0        |        9.0.1        |
|         pip         |        21.3.1       |        22.0.3       |
|     prettytable     |        2.4.0        |        3.0.0        |
|      pyopenssl      |        21.0.0       |        22.0.0       |
| python-libarchive-c |         3.2         |         4.0         |
|         qtpy        |        1.11.3       |        2.0.1        |
|      setuptools     |        50.3.2       |        59.8.0       |
|       tifffile      |      2021.11.2      |       2022.2.2      |
|        tomli        |        1.2.2        |        2.0.1        |
|       pyarrow       |        6.0.1        |        7.0.0        |

Packages With Degraded Versions
-------------------------------

|     Package     |  Old   |  New   |
|:---------------:|:------:|:------:|
|    pyqtgraph    | 0.11.1 | 0.11.0 |
| python-graphviz |  0.19  |  0.17  |

### CODE REVIEW

**Comment by ZLLentz** [comment]
All the unit tests pass, but there are some packaging issues that need closer attention

**Comment by ZLLentz** [comment]
Summary of symptoms:
- `lightpath --help` errors out on the import of pyepics, which imports from `pkg_resources` which raises `pkg_resources.DistributionNotFound: The 'typhos>=1.0.0' distribution was not found and is required by lightpath
`
- `pip check` finds that `pydm 1.12.0 has requirement pyqtgraph==0.11.0, but you have pyqtgraph 0.11.1`

Thoughts and where I'm checking first:
- Using my local construction of this env, I can verify the above failures
- I want to look closely at how `typhos` is packaged- we clearly have a high enough version installed
- I want to look closely at how `pydm` is packaged- I thought this was a desync between setup.py requirements and conda requirements, but they seem to match on master
- Maybe there's a bug in a central library like `pip` or even in `python` itself that needs to be held back?

**Comment by ZLLentz** [comment]
Ok, so the last `pydm` tag `v1.12.0` has `pyqtgraph` pinned down in setup.py/requirements.txt but not in the conda recipe, which causes this build issue. The motivation was py2/py3 support, which is dropped in the next tag.
Relevant PRs:
https://github.com/slaclab/pydm/pull/776
https://github.com/slaclab/pydm/pull/783

Two options:
- Don't update `pydm`
- pin `pyqtgraph` ourselves

Consequences of not updating `pydm`:
- We don't get to use local/calc plugins
- We don't get multiple y axes on plots
- We don't get recent bugfixes

Consequences of pinning `pyqtgraph` back once:
- We regress the environment
- We lose 266 commits and 129 files changed of bugfixes

**Comment by klauer** [comment]
`pydm` is probably more important overall, if we have to choose.

Can we get the pydm team to fix the build deps and retag in a reasonable period of time?

**Comment by ZLLentz** [comment]
Pydm's build deps are already fixed in one of those PRs I linked. Breaking the deps was intentional, the desync with conda-forge probably was not.

I'm leaning towards pinning `pyqtgraph` because our main consumer of it is `pydm` and that's what the tag was tested on.

The history of `pyqtgraph` in our env is strange, it was at `0.12.0` for the longest time and then something regressed it to `0.11.1` ten months ago, where it remains up to now.

**Comment by ZLLentz** [comment]
Suspicious PR: https://github.com/pcdshub/pcds-envs/pull/186

**Comment by klauer** [comment]
I meant to sync the conda-forge pin, but perhaps I still don't understand fully the issue at hand...

**Comment by ZLLentz** [comment]
The conda recipe only causes an issue in that it allows us to install a dependency that will be rejected by pip check etc., functionally all the unit tests pass, but if dependency resolution is checked then an exception is raised.

**Comment by ZLLentz** [comment]
Ok neat all the normal tests pass!

The bonus tests fail at:
py39 dev/master:
```
Encountered problems while solving:
  - package 'transfocate-0.5.5-pyhd8ed1ab_0' is excluded by strict repo priority
```
py310:
```
Encountered problems while solving:
  - package pyca-3.1.1-py39hde0f152_2 requires python_abi 3.9.* *_cp39, but none of the providers can be installed
```

Next step: I will generate the release notes by pressing the generate release notes button

**Comment by ZLLentz** [comment]
I will now start my self-review and open up the pr for other reviews

**Comment by ZLLentz** [comment]
I'm considering taking a moment to extend the automatic release notes writer:
- It'd be nice to show the packages with degraded versions in their own section
- It'd be nice for the "new dependencies" section to show the full chain up to what packages we specified

**Review by klauer — APPROVED** [review]
I think this all looks good and that you made the right choice with the issue above.

Interesting to see a new dep for Python itself (libnsl). I know I've complimented it before, but that auto-diff is just fantastic.

I was a bit surprised to not find whatrecord here, but then I realized I don't have CD configured for PyPI releases. I have since pushed it - but given where you are in the env release process, please don't feel obligated to re-run things. It can always be picked up in the next tagging round. It'll remove apischema pinning and change more than just whatrecord, just so you know.

**Review by tangkong — APPROVED** [review]

**Comment by ZLLentz** [comment]
New release note part for when the version goes down, since we pinned something back and it didn't even get a footnote in the docs here:

Packages With Degraded Versions
-------------------------------

|  Package  |  Old   |  New   |
|:---------:|:------:|:------:|
| pyqtgraph | 0.11.1 | 0.11.0 |

**Comment by tangkong** [comment]
pretty neat!  Nobody needs regex anymore?

**Comment by ZLLentz** [comment]
I'm not really sure what happened to `regex`, I wish I knew a good way to quickly evaluate the "removed" packages. Maybe activating the old environment and running... something?

**Comment by klauer** [comment]
`regex` is an optional `lark` dependency - faster than `re`. That's the only place I know it from (as `blark`'s optional sub-dependency).

**Comment by ZLLentz** [comment]
Here's what the previous env has to say about `regex`:
```
$ pipdeptree --reverse -p regex
regex==2021.11.10
  - black==21.11b1 [requires: regex>=2021.4.4]
    - papermill==2.3.3 [requires: black]
```

**Comment by ZLLentz** [comment]
It looks like the newest `black` doesn't require `regex` any more so it was dropped :shrug:
I am very much interested in if there is a way to figure this out generically without activating the old environment... but maybe generically with the old environment is fine too for the notes:
"removed regex, previously required by black"

**Comment by ZLLentz** [comment]
Ok, I'll stick around here and improve the notes a bit. I think it's worthwhile to maximize these since the script gets re-used at each tag.

**Comment by klauer** [comment]
Right, doing it automatically - that's difficult. I'd imagine the answer is "probably not without inspecting the old env" as you've done above.
Could your script gather the removed deps, activate the old env (if available), and report that information?

**Comment by ZLLentz** [comment]
If the "next tag" version of the CI passed with `whatrecord` I'll include the `whatrecord` tag here too

**Comment by ZLLentz** [comment]
> Right, doing it automatically - that's difficult. I'd imagine the answer is "probably not without inspecting the old env" as you've done above. Could your script gather the removed deps, activate the old env (if available), and report that information?

Do you know how to activate a conda env from inside a python script? Maybe I have to shell out, activate, and have the shell run the script recursively??

**Comment by ZLLentz** [comment]
Or instead, make a bash wrapper- maybe that's the prudent solution. Run it twice with two different envs and different args.

**Comment by klauer** [comment]
I'm sure it's doable _somehow_ in Python, but your bash wrapper seems much easier...

**Comment by ZLLentz** [comment]
Once more around with making the `whatrecord` update inclusion officially included, should be fine, and then one more run of the release notes maker and we're probably good.

**Comment by ZLLentz** [comment]
It looks like the exported yaml fails to be installable from conda if it contains `graphviz` because the installed name is `python-graphviz` but the name you use on pypi is just `graphviz`.

To fix this, I'm going to pin `graphviz` in `conda-packages.txt` to an ok level for `whatrecord` to keep it as a conda install.

**Comment by ZLLentz** [comment]
Note that it is only the install-via-yaml that is broken here, not the environment itself.

**Comment by ZLLentz** [comment]
Ok this package literally has two different names, making this very confusing to handle. I'm going to write out what I think is happening to help myself understand:

On conda-forge, we have:
`python-graphviz` (v0.19.1)-> depends on `graphviz`
`graphviz` (v2.50.0) -> replacement for a system install of graphviz

On pypi we have:
`graphviz` (v0.19.1) -> depends on a system install of graphviz, installs as `python-graphviz`

So, I think this is what happens during the install steps:
1. `python-graphviz` is specified in `conda-packages.txt`, so it is installed in the mamba step at `v0.19.1` alongside `graphviz=v2.50.0`  (latest)
2. `whatrecord` specifies `graphviz <0.18`, so when we pip install it it checks what `graphviz` is, finds the `python-graphviz` package, and says "great, let's downgrade versions", which goes well
3. An environment gets created that works perfectly
4. An environment yaml is exported, and it includes `python-graphviz` in the `pip` section
5. Later, when we unpack the yaml, we check `pypi` for a package named `python-graphviz`, but it does not exist and the build fails.

I guess the solution is to pin `python-graphviz` in `conda-packages.txt` and hope for the best. This is where I'll start.

**Comment by ZLLentz** [comment]
Phew, everything looks golden! I'm going to step through the remaining tag/deploy steps!

**Comment by klauer** [comment]
What a rollercoaster ride - thanks for the hard work here, @ZLLentz!

**Pull request merged**
