### PR TITLE
BLD: remove tiled from requirements, pin numpy < 2.0

### PR DESCRIPTION
**Pull request by tangkong**
Remove tiled from our dependency list, given there are no direct consumers of it.  We may possibly also use this to evaluate removing other regressive pins 

TO-DO:
- try removing databroker<2.0.0 pin , to pick up recent numpy 2.0 bugfixes  (previously pinned in #261)
- try removing ophyd==1.7.0 pin, ophyd v2 development has moved to ophyd-async, and the latest version of ophyd was released in Sept 2023.  I expect if we get ophyd 1.9.0 to work we won't have to do much else.
- maybe sphinx/rtd_theme incompat?...

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
Something weird going on in the py39 builds
```
2024-06-20T22:36:57.4736826Z pip_check_start
2024-06-20T22:37:00.4362457Z pcdscalc 0.5.1 requires xraylib, which is not installed.
2024-06-20T22:37:00.5205111Z pip_check_end
2024-06-20T22:37:00.5205610Z pip_audit_start
2024-06-20T22:37:00.5211043Z pip audit results:
2024-06-20T22:37:57.8527642Z Traceback (most recent call last):
2024-06-20T22:37:57.8528966Z   File "/home/runner/work/pcds-envs/pcds-envs/scripts/pip_audit_markdown.py", line 75, in <module>
2024-06-20T22:37:57.8529811Z     exit(main())
2024-06-20T22:37:57.8530833Z   File "/home/runner/work/pcds-envs/pcds-envs/scripts/pip_audit_markdown.py", line 62, in main
2024-06-20T22:37:57.8531878Z     table = format_results(get_results())
2024-06-20T22:37:57.8533158Z   File "/home/runner/work/pcds-envs/pcds-envs/scripts/pip_audit_markdown.py", line 26, in get_results
2024-06-20T22:37:57.8534291Z     return json.loads(process.stdout)
2024-06-20T22:37:57.8535502Z   File "/home/runner/miniconda/envs/pcds-test/lib/python3.9/json/__init__.py", line 346, in loads
2024-06-20T22:37:57.8538748Z     return _default_decoder.decode(s)
2024-06-20T22:37:57.8540028Z   File "/home/runner/miniconda/envs/pcds-test/lib/python3.9/json/decoder.py", line 337, in decode
2024-06-20T22:37:57.8541141Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-06-20T22:37:57.8542358Z   File "/home/runner/miniconda/envs/pcds-test/lib/python3.9/json/decoder.py", line 355, in raw_decode
2024-06-20T22:37:57.8545294Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-06-20T22:37:57.8546059Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-06-20T22:37:57.8578344Z pip_audit_end
```

**Comment by ZLLentz** [comment]
I think this is a correct change

**Comment by tangkong** [comment]
Also `p4p` uses `numpy.distutils` on build, which does not exist for python 3.12.
xraylib (used by pcdscalc) needs to be updated to support numpy 2.0
...

**Comment by ZLLentz** [comment]
I think we definitely will need to pin numpy<2 for now in the builds here

**Comment by tangkong** [comment]
After pinning numpy<2, a few errors persist.
* `p4p`'s build process requires `numpy.distutils`, which was deprecated for python 3.12 (different from a numpy error).  There is a stalled pull request that promises to fix this https://github.com/mdavidsaver/p4p/pull/141
* in py3.9, `xraylib` gets installed but can't be found by pip check.

**Comment by ZLLentz** [comment]
It kind of seems like jumping to python 3.12 will be rough, maybe we should wait to jump or settle for 3.11 for the next big shift

**Comment by ZLLentz** [comment]
I also added #335 to capture how e.g. py313-readiness should be failing here

**Review by ZLLentz — APPROVED** [review]
Still re-affirming that all the changes here are correct

**Comment by ZLLentz** [comment]
I'm going to merge this before proceeding to other packaging updates for the upcoming tag storm

**Pull request merged**
