### PR TITLE
ENH: updated pcds to 5.7.3

### PR DESCRIPTION
**Pull request by ZLLentz**
A few more things to consider before accepting this:
- Does `slac-alarm-manager` belong here, or installed separately?
  - Is there any importable bits that would be useful elsewhere?
  - Will we need to update this between pcds_conda environment builds?
- Should the missing `jet_tracking` dependency be added here?
  - Probably not? We should instead install `jet_tracking` itself once we fix up the dependencies?
  - Or should this also be installed separately like other app-only things?

I'll ignore all of this in favor of getting the unit tests churning, here and on psbuild

PCDS Package Updates
--------------------

|   Package   |  Old   |  New   |                       Release Notes                        |
|:-----------:|:------:|:------:|:----------------------------------------------------------:|
|    happi    | 2.2.0  | 2.3.0  |    https://github.com/pcdshub/happi/releases/tag/v2.3.0    |
|   pcdscalc  | 0.4.1  | 0.4.2  |  https://github.com/pcdshub/pcdscalc/releases/tag/v0.4.2   |
| pcdsdevices | 7.4.0  | 7.4.3  | https://github.com/pcdshub/pcdsdevices/releases/tag/v7.4.1<br>https://github.com/pcdshub/pcdsdevices/releases/tag/v7.4.2<br>https://github.com/pcdshub/pcdsdevices/releases/tag/v7.4.3 |
|    pytmc    | 2.15.0 | 2.15.1 |   https://github.com/pcdshub/pytmc/releases/tag/v2.15.1    |

SLAC Package Updates
--------------------

| Package |  Old   |  New   |                    Release Notes                     |
|:-------:|:------:|:------:|:----------------------------------------------------:|
|   pydm  | 1.19.0 | 1.19.1 | https://github.com/slaclab/pydm/releases/tag/v1.19.1 |

Lab Community Package Updates
-----------------------------

| Package |  Old  |  New  |
|:-------:|:-----:|:-----:|
| caproto | 1.0.1 | 1.1.0 |

Python Community Core Package Updates
-------------------------------------

| Package |  Old  |  New  |
|:-------:|:-----:|:-----:|
|  pytest | 7.3.1 | 7.4.0 |

Packages With Degraded Versions
-------------------------------

| Package  |  Old   |  New   |
|:--------:|:------:|:------:|
| markdown | 3.4.3  | 3.3.7  |

Added the Following Packages
----------------------------

- atef
- mkdocs-material
- mkdocstrings
- pytkdocs
- slac-alarm-manager

Added the Following Dependencies
--------------------------------

- astunparse (required by pytkdocs)
- codecov (required by mpmath, networkx, pydm, whatrecord, which are used in ads-async, bluesky, bluesky-live, databroker, happi, hutch-python, ipython, jupyter, nabs, ophyd, pcdscalc, pcdsdevices, pcdsutils, scikit-image, suitcase-tiff, tiled, transfocate, typhos, xarray)
- commonmark (required by recommonmark, sphinx-argparse, which are used in lucid, pcdscalc, pytmc, whatrecord)
- docstring_parser (required by pytkdocs)
- doctr (required by atef, happi)
- ghp-import (required by mkdocs)
- kafka-python (required by slac-alarm-manager)
- mergedeep (required by mkdocs)
- mkdocs (required by mkdocs-autorefs, mkdocs-material, mkdocstrings)
- mkdocs-autorefs (required by mkdocstrings)
- mkdocs-material-extensions (required by mkdocs-material)
- nbsphinx (required by hutch-python)
- pymdown-extensions (required by mkdocs-material, mkdocstrings)
- pytest-cov (required by asteval, botorch, fsspec, happi, ipykernel, ipywidgets, jupyter-core, lz4, memray, mock, mpmath, networkx, numcodecs, numpydoc, patsy, pkginfo, pydm, pytmc, qtpy, whatrecord, which are used in ads-async, bluesky, bluesky-live, databroker, hutch-python, ipython, jupyter, lightpath, lucid, nabs, ophyd, pcdscalc, pcdsdevices, pcdsutils, pcdswidgets, scikit-image, suitcase-tiff, tiled, timechart, transfocate, typhos, xarray)
- pyyaml-env-tag (required by mkdocs)
- recommonmark (required by atef, epicsmacrolib, pcdscalc, which are used in whatrecord)
- sphinx-argparse (required by lucid, pytmc)
- sphinx-autodoc-typehints (required by anyio, botorch, graphviz, pytmc, which are used in ipython, jupyter, tiled, whatrecord)
- sphinx-click (required by happi)
- sphinx-copybutton (required by ads-async, atef, epicsmacrolib, pcdscalc, pcdsutils, which are used in whatrecord)
- sphinxcontrib-websupport (required by pytmc, sphinx)
- watchdog (required by mkdocs, werkzeug)

### CODE REVIEW

**Comment by ZLLentz** [comment]
My markdown table is having a bad day here but I'm not sure what to do about it

**Comment by tangkong** [comment]
We never really nailed down the whole venv-process did we?  I think for this iteration `slam` can stay in the env, as it'll (ideally?) be used more widely for nalms, and we can leave `jet_tracking` out and install it in a venv since it's seeing more limited use?

**Comment by tangkong** [comment]
py310 full fails due to the typhos tests zach fixed recently

**Review by tangkong — APPROVED** [review]
I think this looks right, ignoring the stalled py39-full build

**Comment by ZLLentz** [comment]
I'll let this bubble overnight and look to merge tomorrow

**Comment by klauer** [comment]
~Posthumous~ Post-merge LGTM

**Pull request merged**
