### PR TITLE
MAINT: post pcds-5.5.1 tweaks

### LINKED ISSUE #257: Add modern gdb to environment for old systems
https://anaconda.org/conda-forge/gdb

### PR DESCRIPTION
**Pull request by ZLLentz**
These won't become a new env yet but I want to do them while they're on my mind.
- unpin scikit-image because it is blocking py310. Regardless of pinning, this won't be updated in live envs until the python update.
- closes #257 
- re-order the deploy hosts lists to hit the host that asks me for password auth first, so I can do that and then walk away to work on other things
- retry on timeouts for more clear results

### CODE REVIEW

**Comment by ZLLentz** [comment]
Oh man I didn't even change that much I didn't expect the CI to freak out

**Comment by klauer** [comment]
`lightpath/tests/test_gui.py::test_app_buttons Test timed out after 10 minutes, killed with SIGTERM`

**Comment by klauer** [comment]
I saw this in current but didn't check 'next':
```
======= 425 passed, 3 skipped, 6 xfailed, 1 warning in 413.47s (0:06:53) =======

Test for tests/whatrecord finished with exit code 0
```

**Comment by ZLLentz** [comment]
I'm going to change the "all test runner" to retry on the timeouts... I think it makes sense to keep the build short but I want to see these as "race conditions" in the result instead of "failed all retries"

**Comment by ZLLentz** [comment]
Making the build shorter but requiring me to rerun the whole build feels bad

**Comment by ZLLentz** [comment]
the "next env" is the one that includes the described package changes

**Comment by klauer** [comment]
The next env whatrecord 3.10 gdb plugin is yet another new-to-me failure mode.

It's up to you, but it could potentially be just ignored/skipped in the test suite here if it remains problematic (e.g., `pytest -v whatrecord -k 'not gdb_integration'`)

**Comment by ZLLentz** [comment]
This is currently failing during the setup stage, prior to any testing, with:
```
package lightpath-1.0.1-py_0 is excluded by strict repo priority
```
Which is a bit perplexing. It seems like the yaml specifies the `pcds-tag` version of `lightpath` instead of the `conda-forge` version. I think this means that the `pcds-tag` version is the one that's deployed right now in `pcds-5.5.1`

**Comment by ZLLentz** [comment]
I'm going to let the unit tests run here and see the result. Then, I will push one more commit here to reactivate the python 3.10 job (allowed failure). And then I think this sets us up properly for the next small tag once pydm conda-forge goes through.

**Comment by ZLLentz** [comment]
"Next env" will be broken here and there's nothing I can do about it. I suggest we ignore it. "Current env" should pass.

**Comment by ZLLentz** [comment]
current passing
next failing (will pass after the merge)
3.10 failing + allowed failure (will help give us 3.10 status)

**Comment by ZLLentz** [comment]
Let's move this forward, should be good maintenance.

**Pull request merged**
