### PR TITLE
ENH: pcds-5.5.0

### PR DESCRIPTION
**Pull request by ZLLentz**
PCDS Package Updates
--------------------

|   Package    |  Old   |  New   |                        Release Notes                         |
|:------------:|:------:|:------:|:------------------------------------------------------------:|
|  ads-async   | 0.2.0  | 0.3.0  |   https://github.com/pcdshub/ads-async/releases/tag/v0.3.0   |
|    happi     | 1.14.0 | 2.0.0  |     https://github.com/pcdshub/happi/releases/tag/v2.0.0     |
| hutch-python | 1.17.0 | 1.18.0 | https://github.com/pcdshub/hutch-python/releases/tag/v1.18.0 |
|    hxrsnd    | 0.2.8  | 0.2.9  |    https://github.com/pcdshub/hxrsnd/releases/tag/v0.2.9     |
|  lightpath   | 0.6.9  | 1.0.1  |   https://github.com/pcdshub/lightpath/releases/tag/v1.0.0 https://github.com/pcdshub/lightpath/releases/tag/v1.0.1   |
|    lucid     | 0.9.1  | 0.9.2  |     https://github.com/pcdshub/lucid/releases/tag/v0.9.2     |
|     nabs     | 1.5.0  | 1.5.2  |     https://github.com/pcdshub/nabs/releases/tag/v1.5.1 https://github.com/pcdshub/nabs/releases/tag/v1.5.2      |
| pcdsdevices  | 6.3.0  | 7.0.1  |  https://github.com/pcdshub/pcdsdevices/releases/tag/v7.0.0 https://github.com/pcdshub/pcdsdevices/releases/tag/v7.0.1  |
| pcdswidgets  | 0.7.0  | 0.7.1  |  https://github.com/pcdshub/pcdswidgets/releases/tag/v0.7.1  |
|     pmgr     | 2.1.0  | 2.1.1  |     https://github.com/pcdshub/pmgr/releases/tag/R2.1.1      |
|    pytmc     | 2.13.0 | 2.14.1 |    https://github.com/pcdshub/pytmc/releases/tag/v2.14.0 https://github.com/pcdshub/pytmc/releases/tag/v2.14.1     |
|    typhos    | 2.3.2  | 2.3.3  |    https://github.com/pcdshub/typhos/releases/tag/v2.3.3     |
|  whatrecord  | 0.3.5  | 0.4.1  |  https://github.com/pcdshub/whatrecord/releases/tag/v0.4.0 https://github.com/pcdshub/whatrecord/releases/tag/v0.4.1   |

SLAC Package Updates
--------------------

|  Package  |  Old   |  New   |                      Release Notes                       |
|:---------:|:------:|:------:|:--------------------------------------------------------:|
|    pydm   | 1.16.3 | 1.17.0 |   https://github.com/slaclab/pydm/releases/tag/v1.17.0   |
| timechart | 1.5.0  | 1.5.1  | https://github.com/slaclab/timechart/releases/tag/v1.5.1 |

Lab Community Package Updates
-----------------------------

| Package |  Old  |  New   |
|:-------:|:-----:|:------:|
| bluesky | 1.8.3 | 1.10.0 |
| caproto | 0.8.1 | 1.0.0  |
|  ophyd  | 1.6.4 | 1.7.0  |

Other Python Community Major Updates
------------------------------------

|   Package    |  Old   |  New   |
|:------------:|:------:|:------:|
| cryptography | 37.0.2 | 38.0.2 |
|   openssl    | 1.1.1q | 3.0.5  |

Added the Following Packages
----------------------------

- yarn

Added the Following Dependencies
--------------------------------

- epicsmacrolib (required by whatrecord)
- libuv (required by nodejs)
- nodejs (required by yarn)

### CODE REVIEW

**Comment by ZLLentz** [comment]
Offline test failures:
- `hutch-python`: possibly fixed in tag, looks like what the commits describe as being fixed
- `lightpath`: `test_filtering`, don't fully understand the traceback yet
- `whatrecord`: almost everything fails with lark cache permissions error, a known lark issue I think

**Comment by ZLLentz** [comment]
```
    def test_filtering(lightapp: LightApp, monkeypatch):
        lightapp.destination_combo.setCurrentIndex(4)  # set current to MEC
        # Create mock functions
        for row in lightapp.rows:
            monkeypatch.setattr(row[0], 'setHidden', Mock())
        # Initialize properly with nothing hidden
        lightapp.filter()
        for row in lightapp.rows:
            row[0].setHidden.assert_called_with(False)
        # Insert at least one device then hide
        device_row = lightapp.rows[2][0]
        device_row.device.insert()
        lightapp.remove_check.setChecked(False)
        # Reset mock
        for row in lightapp.rows:
            row[0].setHidden.reset_mock()
        lightapp.filter()
        for row in lightapp.rows:
            if row[0].device.get_lightpath_state().removed:
>               row[0].setHidden.assert_called_with(True)

lightpath/tests/test_gui.py:90:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Mock id='139856463006736'>, args = (True,), kwargs = {}
expected = call(True), actual = call(False)
_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x7f32dec5bb80>
cause = None

    def assert_called_with(self, /, *args, **kwargs):
        """assert that the last call was made with the specified arguments.

        Raises an AssertionError if the args and keyword args passed in are
        different to the last call to the mock."""
        if self.call_args is None:
            expected = self._format_mock_call_signature(args, kwargs)
            actual = 'not called.'
            error_message = ('expected call not found.\nExpected: %s\nActual: %s'
                    % (expected, actual))
            raise AssertionError(error_message)

        def _error_message():
            msg = self._format_mock_failure_message(args, kwargs)
            return msg
        expected = self._call_matcher(_Call((args, kwargs), two=True))
        actual = self._call_matcher(self.call_args)
        if actual != expected:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: expected call not found.
E           Expected: mock(True)
E           Actual: mock(False)
```

**Comment by klauer** [comment]
> whatrecord: almost everything fails with lark cache permissions error, a known lark issue I think

Can you try updating lark-parser? There's a new version that may fix this

**Comment by ZLLentz** [comment]
After checking against hutch-python's master branch, only things remain that look like they may be handled in https://github.com/pcdshub/hutch-python/pull/350

I'm trying to update my lark, conda is being slow

**Comment by ZLLentz** [comment]
Updating lark made the `whatrecord` tests actually run
There's still something funky going on with the parsing tests, I don't suppose I need to add `epicsmacrolib` to the always update list?

```

whatrecord/bin/parse.py:196: in main
    write_to_file(result, filename=output, format=output_format)
whatrecord/util.py:277: in write_to_file
    json_info = apischema.serialize(obj)
../../../../../miniconda3/envs/pcds-5.5.0/lib/python3.9/site-packages/apischema/utils.py:400: in wrapper
    return wrapped(*args, **kwargs)
../../../../../miniconda3/envs/pcds-5.5.0/lib/python3.9/site-packages/apischema/serialization/__init__.py:660: in serialize
    return serialization_method(
apischema/serialization/methods.pyx:94: in apischema.serialization.methods.AnyMethod.serialize
    ???
apischema/serialization/methods.pyx:95: in apischema.serialization.methods.AnyMethod.serialize
    ???
apischema/serialization/methods.pyx:476: in apischema.serialization.methods.AnyMethod_serialize
    ???
apischema/serialization/methods.pyx:675: in apischema.serialization.methods.SerializationMethod_serialize
    ???
apischema/serialization/methods.pyx:529: in apischema.serialization.methods.ObjectMethod_serialize
    ???
apischema/serialization/methods.pyx:711: in apischema.serialization.methods.BaseField_update_result
    ???
apischema/serialization/methods.pyx:605: in apischema.serialization.methods.SimpleField_update_result
    ???
apischema/serialization/methods.pyx:675: in apischema.serialization.methods.SerializationMethod_serialize
    ???
apischema/serialization/methods.pyx:529: in apischema.serialization.methods.ObjectMethod_serialize
    ???
apischema/serialization/methods.pyx:711: in apischema.serialization.methods.BaseField_update_result
    ???
apischema/serialization/methods.pyx:605: in apischema.serialization.methods.SimpleField_update_result
    ???
apischema/serialization/methods.pyx:695: in apischema.serialization.methods.SerializationMethod_serialize
    ???
apischema/serialization/methods.pyx:583: in apischema.serialization.methods.ConversionMethod_serialize
    ???
whatrecord/macro.py:49: in _serialize_macro_context
    macros=dict(ctx),
epicsmacrolib/macro.pyx:206: in _epicsmacrolib.macro._MacroContext.__getitem__
    ???
../../../../../miniconda3/envs/pcds-5.5.0/lib/python3.9/site-packages/epicsmacrolib/macro.py:159: in expand
    return self._expand(value, empty_on_failure=empty_on_failure)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: For large strings, use `expand_with_length`
```

**Comment by klauer** [comment]
`epicsmacrolib` should be added to the always-update list. 

Which test is failing specifically? I don't see it in your output.

**Comment by ZLLentz** [comment]
it's on the travis now- most of parsing tests, with the same error, but probably not with the newest macrolib

**Comment by ZLLentz** [comment]
This does pass now. I'll run it one more time after the hutch-python tag can be squeezed in and then it will be time to generate release notes.

**Comment by ZLLentz** [comment]
I expect the latest commit brings us to the fully intended conda release. The conda pack is packing right now and it is time to generate the release notes and run the full test suite on psbuild.

**Comment by ZLLentz** [comment]
On travis:
- this env test failed with a 10 minute timeout on `lightpath/tests/test_gui.py::test_upstream_check
- next env test (nominally, the exact same test right now) had a race condition where `lightpath/tests/test_gui.py::test_filtering` failed once but passed the next time

<details>

```
=================================== FAILURES ===================================
________________________________ test_filtering ________________________________
lightapp = <lightpath.ui.gui.LightApp object at 0x7faf975e80d0>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7faf9c1b37f0>
    def test_filtering(lightapp: LightApp, monkeypatch):
        lightapp.destination_combo.setCurrentIndex(4)  # set current to MEC
        # Create mock functions
        for row in lightapp.rows:
            monkeypatch.setattr(row[0], 'setHidden', Mock())
        # Initialize properly with nothing hidden
        lightapp.filter()
        for row in lightapp.rows:
            row[0].setHidden.assert_called_with(False)
        # Insert at least one device then hide
        device_row = lightapp.rows[2][0]
        device_row.device.insert()
        lightapp.remove_check.setChecked(False)
        # Reset mock
        for row in lightapp.rows:
            row[0].setHidden.reset_mock()
        lightapp.filter()
        for row in lightapp.rows:
            if row[0].device.get_lightpath_state().removed:
>               row[0].setHidden.assert_called_with(True)
lightpath/tests/test_gui.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <Mock id='140392215288080'>, args = (True,), kwargs = {}
expected = call(True), actual = call(False)
_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x7faf9762c9d0>
cause = None
    def assert_called_with(self, /, *args, **kwargs):
        """assert that the last call was made with the specified arguments.
    
        Raises an AssertionError if the args and keyword args passed in are
        different to the last call to the mock."""
        if self.call_args is None:
            expected = self._format_mock_call_signature(args, kwargs)
            actual = 'not called.'
            error_message = ('expected call not found.\nExpected: %s\nActual: %s'
                    % (expected, actual))
            raise AssertionError(error_message)
    
        def _error_message():
            msg = self._format_mock_failure_message(args, kwargs)
            return msg
        expected = self._call_matcher(_Call((args, kwargs), two=True))
        actual = self._call_matcher(self.call_args)
        if actual != expected:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: expected call not found.
E           Expected: mock(True)
E           Actual: mock(False)
../../../miniconda/envs/pcds-next-incr/lib/python3.9/unittest/mock.py:907: AssertionError
```

</details>

I am going to re-run the travis build to see if any of this was a fluke.

**Comment by ZLLentz** [comment]
Result output from the psbuild test suite:
```
The following packages failed all retries:
tests/whatrecord
The following packages had race conditions, but passed at least once:
tests/lightpath
tests/pcdsdaq
Extra tests passed
No broken requirements found
```
`whatrecord` failure (failed 5 times):
<details>

```
=================================== FAILURES ===================================
________________________________ test_gdb_info _________________________________

    @platform_skip
    @gdb_unavailable_skip
    @softioc_unavailable_skip
    def test_gdb_info():
        md = IocMetadata(binary=str(softioc))

        async def inner() -> Optional[GdbBinaryInfo]:
            return await md.get_binary_information()

        loop = asyncio.get_event_loop()
        info = loop.run_until_complete(inner())

        assert info is not None, "Script appears to have failed"
        print("Got information", info)

>       assert len(md.variables)
E       AssertionError: assert 0
E        +  where 0 = len({})
E        +    where {} = IocMetadata(name='unset', script=PosixPath('.'), startup_directory=PosixPath('.'), host=None, port=None, binary='/reg/...egisterRecordDeviceDriver.cpp': '8c8fa6c8de3f0f6bdbf9bb227c678070f5311606e7b8e9899b8932c3564a7f32'}, load_success=True).variables

whatrecord/tests/test_gdb_integration.py:47: AssertionError
```

</details>

`lightpath` intermittent failure (failed once):
<details>

```
________________________________ test_callback _________________________________

path = BeamPath(range=(0.0, 30.0), devices=11)

    def test_callback(path: BeamPath):
        # Create mock callback
        cb = Mock()
        # Subscribe to event changes
        path.subscribe(cb, run=False)
        # Change state of beampath
        path.devices[4].insert()
        # Assert callback has been run
>       assert cb.called
E       AssertionError: assert False
E        +  where False = <Mock id='140651858531136'>.called

lightpath/tests/test_path.py:207: AssertionError

```

</details>

`pcdsdaq` intermittent failure (failed once):
<details>

```
_______________________________ test_basic_plans _______________________________

daq = <pcdsdaq.daq.Daq object at 0x7f3ed47a12b0>
RE = <bluesky.run_engine.RunEngine object at 0x7f3ed47a9e50>

    @pytest.mark.timeout(10)
    def test_basic_plans(daq, RE):
        logger.debug('test_basic_plans')
        daq.configure(events=12)

        start = time.time()
        RE(stage_wrapper(run_wrapper(trigger_and_read([daq])), [daq]))
        dt = time.time() - start
>       assert 0.1 < dt < 0.2
E       assert 0.20763921737670898 < 0.2

tests/test_daq.py:330: AssertionError
```

</details>

**Comment by tangkong** [comment]
In the past I'd seen a lightpath failure similar to that, tracing back to earlier tests leaking and placing that device in an inserted state at the beginning of the test (causing the callback to never fire).  I went to considerable lengths to make sure devices weren't cached, though...  

I also can't reproduce this locally but maybe that's a given

**Comment by ZLLentz** [comment]
2nd travis run had the other build run into the stall/timeout instead
I think these failures don't indicate a need to hold back the env but probably they should be addressed later

**Review by tangkong — APPROVED** [review]
Updates to the env look good to me.  Test failures aside, I like the what the minimal update procedure does for the env diff.

After sitting through some recent collaboration calls, I'm wary of bluesky/ophyd updates in general, though these version bumps should be fine.  

What constitutes a major version number increase here?  There are a lot of api changes thanks to lightpath but there's been crazier changes in the past I'm sure?

**Comment by ZLLentz** [comment]
> What constitutes a major version number increase here? There are a lot of api changes thanks to lightpath but there's been crazier changes in the past I'm sure?

I left these guidelines for myself earlier in the year, they can be revised as needed:

>Updating the third "bugfix" number means that only core packages that we work on ourselves were updated.
Updating the second "minor" number means that other packages were also updated.
Updating the first "major" number means that we updated Python itself to a new non-bugfix version. For example, this number will be incremented when update to python 3.10.0, but not when we update to python 3.9.14.

**Comment by ZLLentz** [comment]
I'm going to start making the summary confluence page for this. If I finish that before Ken is able to take a look we'll merge without his green check- I suspect this is a fairly uncontroversial tag.

**Pull request merged**
