### PR TITLE
ENH:  pcds-5.4.0

### LINKED ISSUE #226: Reclassify elog in release notes table
Release notes are on pcdshub
So it should be a pcds package, not a slac package

### LINKED ISSUE #229: Evaluate memray and consider adding it to our environment
Link: https://github.com/bloomberg/memray

> Memray is a memory profiler for Python. It can track memory allocations in Python code, in native extension modules, and in the Python interpreter itself. It can generate several different types of reports to help you analyze the captured memory usage data. While commonly used as a CLI tool, it can also be used as a library to perform more fine-grained profiling tasks.

### LINKED ISSUE #231: Add rich
useful terminal output tool, atef dependency

### PR DESCRIPTION
**Pull request by ZLLentz**
never deploy on a friday

closes #226
closes #229
closes #231

PCDS Package Updates
--------------------

|   Package    |  Old   |  New   |                        Release Notes                         |
|:------------:|:------:|:------:|:------------------------------------------------------------:|
|    blark     | 0.3.0  | 0.4.0  |     https://github.com/klauer/blark/releases/tag/v0.4.0     |
| hutch-python | 1.14.0 | 1.15.0 | https://github.com/pcdshub/hutch-python/releases/tag/v1.15.0 |
|     krtc     | 0.1.4  | 0.2.0  |     https://github.com/pcdshub/krtc/releases/tag/v0.2.0      |
|     nabs     | 1.3.0  | 1.4.0  |     https://github.com/pcdshub/nabs/releases/tag/v1.4.0      |
| pcdsdevices  | 5.2.0  | 6.0.0  |  https://github.com/pcdshub/pcdsdevices/releases/tag/v6.0.0  |
|  pcdsutils   | 0.8.0  | 0.9.0  |   https://github.com/pcdshub/pcdsutils/releases/tag/v0.9.0   |
| pcdswidgets  | 0.6.0  | 0.7.0  |  https://github.com/pcdshub/pcdswidgets/releases/tag/v0.7.0  |
|    typhos    | 2.3.0  | 2.3.1  |    https://github.com/pcdshub/typhos/releases/tag/v2.3.1     |
|  whatrecord  | 0.3.1  | 0.3.5  |  https://github.com/pcdshub/whatrecord/releases/tag/v0.3.5   |

SLAC Package Updates
--------------------

|   Package   |  Old   |  New   |                       Release Notes                        |
|:-----------:|:------:|:------:|:----------------------------------------------------------:|
| psdm_qs_cli | 0.3.1  | 0.3.5  | https://github.com/slaclab/psdm_qs_cli/releases/tag/v0.3.5 |
|     pydm    | 1.14.0 | 1.15.1 |    https://github.com/slaclab/pydm/releases/tag/v1.15.1    |

Lab Community Package Updates
-----------------------------

|      Package      |   Old    |   New    |
|:-----------------:|:--------:|:--------:|
|      bluesky      |  1.8.2   |  1.8.3   |
|     databroker    | 2.0.0a24 | 2.0.0b2  |
|       ophyd       |  1.6.3   |  1.6.4   |
| suitcase-specfile |  0.2.4   |  0.2.5   |
|   suitcase-tiff   |  0.3.0   |  0.4.0   |
|       tiled       | 0.1.0a59 | 0.1.0a60 |

Python Community Core Package Updates
-------------------------------------

|  Package   |  Old   |  New   |
|:----------:|:------:|:------:|
|  ipython   | 8.2.0  | 8.3.0  |
| pre-commit | 2.18.1 | 2.19.0 |

Other Python Community Major Updates
------------------------------------

|    Package     |   Old   |  New   |
|:--------------:|:-------:|:------:|
|     bleach     |  4.1.0  | 5.0.0  |
|   libgcc-ng    |  11.2.0 | 12.1.0 |
| libgfortran-ng |  11.2.0 | 12.1.0 |
|  libgfortran5  |  11.2.0 | 12.1.0 |
|  libstdcxx-ng  |  11.2.0 | 12.1.0 |
|  llvm-openmp   |  13.0.1 | 14.0.3 |
|     locket     |  0.2.0  | 1.0.0  |
|   setuptools   | 60.10.0 | 62.2.0 |
|    pyarrow     |  7.0.0  | 8.0.0  |

Added the Following Packages
----------------------------

- memray

Added the Following Dependencies
--------------------------------

- area-detector-handlers (required by databroker)
- atomicwrites (required by lark, which is used in blark, whatrecord)
- commonmark (required by rich, which is used in tiled)
- js2py (required by lark, which is used in blark, whatrecord)
- mongomock (required by databroker)
- pyjsparser (required by js2py, which is used in blark, whatrecord)
- python-fastjsonschema (required by nbformat, which is used in bluesky, bluesky-live, databroker, ipython, jupyter, tiled, xarray)
- rich (required by httpx, memray, which are used in tiled)
- sentinels (required by mongomock, which is used in databroker)
- tinycss2 (required by bleach, nbconvert, nbconvert-core, which are used in bluesky, bluesky-live, databroker, ipython, jupyter, tiled, xarray)
- zlib-ng (required by c-blosc2)

Removed the Following Packages
------------------------------

- asciitree
- fasteners
- intake
- lark-parser
- numcodecs
- testpath
- zarr

### CODE REVIEW

**Comment by ZLLentz** [comment]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by klauer** [comment]
I've got about 4 packages I'd like to make the tag, if possible. Everything else looks fine.

**Comment by ZLLentz** [comment]
Can definitely wait for 4 packages- probably deploying this next week outside of normal hours

**Comment by tangkong** [comment]
Things look good to me, but I suppose I'll wait until those extra packages make it in?

**Comment by ZLLentz** [comment]
Re-running this with recent new tags
Will not get around to updating the release notes in the descriptions until tomorrow

**Review by tangkong — APPROVED** [review]
LGTM

**Comment by ZLLentz** [comment]
Two errors in the output: to investigate later, probably
```
subprocess.CalledProcessError: Command '['conda', 'search', '--json', 'whatrecord']' returned non-zero exit status 1.
RuntimeError: whatrecord not found on pypi.
```

**Comment by ZLLentz** [comment]
Build fails on timeout
Need to check travis docs about extending the no-text-output timeout on specific commands, there was an option for it

**Comment by ZLLentz** [comment]
If I'm interpreting the output right, our internal "fail at 20min" timeout popped after we extended the travis timeout... I'm not super happy about it but I'm going to try to extend both measures to 30min and see what happens.

**Review by klauer — APPROVED** [review]
Aside from the obvious build failure, this all looks fine to me. Sorry the `travis_wait` addition didn't actually help!

**Comment by ZLLentz** [comment]
Just normal CI things: unwrapping failure modes one at a time!

Worst case scenario I'm going to drop the "next env" test to allowed failure in favor of getting the tag out. At this rate, the "start of May" tag will happen in June.

**Comment by ZLLentz** [comment]
It takes 1727s ~ 28.78 minutes just to build the environment now...

**Comment by ZLLentz** [comment]
I'm not a fan of travis_wait right now because it eats all the output from the enclosed function until it finishes, I wonder if it'd be better to just go with a verbose mamba output instead to keep the build log updating

**Comment by ZLLentz** [comment]
We'll stick with travis_wait and deal with the silence- verbose mode isn't verbose enough (without going into full debug/trace mode which seems excessive)

**Comment by ZLLentz** [comment]
However, it might be time to make concessions on the size of the package list. I imagine that package solving gets slower very quickly as we add more dependencies.

**Comment by ZLLentz** [comment]
Regenerating the release notes in case they changed since I last did it

**Comment by ZLLentz** [comment]
OK I am in the mood to merge/tag today and deploy during tomorrow

**Comment by klauer** [comment]
Do you think our pyqt pin of `<5.15` caused the solver to work that much harder? I have an inkling that it did...

**Comment by ZLLentz** [comment]
I don't even think we pinned it in this tag! It must have come from upstream, unless I missed something.

**Comment by ZLLentz** [comment]
But yes. I think pins can bloat the solve time. It might be worth trying == pins so it can't search around... Not sure if that even matters.

**Pull request merged**
