### PR TITLE
ENH: pcds-4.1.0

### PR DESCRIPTION
**Pull request by ZLLentz**
PCDS package updates:
|  Package | Old | New |
| - | - | - |
| ads-async | 0.0.2 | 0.1.0 |
| pcdsdaq | 2.3.3 | 2.3.4 |
| pcdsdevices | 4.2.0 | 4.3.2 |
| pcdsutils | 0.4.1 | 0.4.2 |
| psdaq.control | N/A |  3.3.14 |
| pytmc | 2.8.1 | 2.9.0 |
| transfocate | 0.3.4 | 0.5.0 |
| typhos | 1.1.4 | 1.1.6 |

Lab community package notable updates:
|  Package | Old | New |
| - | - | - |
| caproto | 0.7.1 | 0.8.0 |
| p4p | N/A | 3.5.2 |
| pydm | 1.10.7 | 1.11.0 |
| timechart | 1.2.3 | 1.2.4 |

Python community package notable updates:
|  Package | Old | New |
| - | - | - |
| ipython | 7.21.0 | 7.22.0 |
| matplotlib | 3.3.4 | 3.4.1 |
| numpy | 1.20.1 | 1.20.2 |

### CODE REVIEW

**Comment by klauer** [comment]
Will close #184 👏

**Comment by ZLLentz** [comment]
I'm not sure travis got the memo 😕, cycling

**Comment by ZLLentz** [comment]
```
The following packages failed all retries:
tests/typhos
No packages had race conditions!
Extra tests passed
No broken requirements found.
```

**Comment by ZLLentz** [comment]
Currently waiting on conda-forge builds before the next try with pydm frozen to v1.10.7

**Comment by ZLLentz** [comment]
Ok I have no idea what's happening, my packages are shown on anaconda.org/conda-forge but I cannot search for or install them in my terminal. I have to assume that something is broken somewhere.

**Comment by klauer** [comment]
Oh no... Did your condarc/channels get messed up somehow? 

Maybe send along some `conda search` commands you've tried so I can check to see if I can reproduce?

**Comment by ZLLentz** [comment]
```
$ conda search pcdsdevices -c conda-forge
Loading channels: done
# Name                       Version           Build  Channel
pcdsdevices                    2.4.0            py_0  conda-forge
pcdsdevices                    2.4.0            py_1  conda-forge
pcdsdevices                    2.4.0            py_2  conda-forge
pcdsdevices                    2.5.0            py_0  conda-forge
pcdsdevices                    2.6.0            py_0  conda-forge
pcdsdevices                    2.7.0            py_0  conda-forge
pcdsdevices                    2.8.0            py_0  conda-forge
pcdsdevices                    2.9.0            py_0  conda-forge
pcdsdevices                   2.10.0            py_0  conda-forge
pcdsdevices                   2.11.0            py_0  conda-forge
pcdsdevices                    3.0.0            py_0  conda-forge
pcdsdevices                    3.1.0            py_0  conda-forge
pcdsdevices                    3.2.0            py_0  conda-forge
pcdsdevices                    3.3.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.0.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.1.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.2.0    pyhd8ed1ab_0  conda-forge
```
Missing 4.3.0

**Comment by klauer** [comment]
Mine:

```
$ conda search pcdsdevices -c conda-forge
Loading channels: done
# Name                       Version           Build  Channel
pcdsdevices                    2.4.0            py_0  conda-forge
pcdsdevices                    2.4.0            py_1  conda-forge
pcdsdevices                    2.4.0            py_2  conda-forge
pcdsdevices                    2.5.0            py_0  conda-forge
pcdsdevices                    2.6.0            py_0  conda-forge
pcdsdevices                    2.7.0            py_0  conda-forge
pcdsdevices                    2.8.0            py_0  conda-forge
pcdsdevices                    2.9.0            py_0  conda-forge
pcdsdevices                   2.10.0            py_0  conda-forge
pcdsdevices                   2.11.0            py_0  conda-forge
pcdsdevices                    3.0.0            py_0  conda-forge
pcdsdevices                    3.1.0            py_0  conda-forge
pcdsdevices                    3.2.0            py_0  conda-forge
pcdsdevices                    3.3.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.0.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.1.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.2.0    pyhd8ed1ab_0  conda-forge
pcdsdevices                    4.3.0    pyhd8ed1ab_0  conda-forge
```

**Comment by ZLLentz** [comment]
wtf

**Comment by klauer** [comment]
You're not being a web-caching proxy or anything are you?

**Comment by ZLLentz** [comment]
I'll look at this again after doing gateway work

**Comment by klauer** [comment]
FWIW, trying to create the env from this PR works in docker (had to as I'm on macOS):

```
$ docker run -it --mount $PWD:/pcds-envs continuumio/miniconda3

(base) root@353e133fb874:/pcds-envs# conda env create -n myenvname -f envs/pcds/env.yaml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
opencv-4.5.1         | 21 KB     | ############################################################################################## | 100%
python-ldap-3.3.1    | 168 KB    | ############################################################################################## | 100%
ansiwrap-0.8.4       | 9 KB      | ############################################################################################## | 100%
shellcheck-0.7.1     | 1.7 MB    | ############################################################################################## | 100%
```

**Comment by ZLLentz** [comment]
I can now see the new pcdsdevices release- not sure what was wrong before. Running again to see green, running one final time once v4.3.1 is online

**Comment by klauer** [comment]
Probably some server (CDN?) between you and anaconda.org cached some stale values. Glad to see it's showing up now, at least!

**Comment by ZLLentz** [comment]
My local (SLAC) build continues to fail because it cannot see pytmc's v2.9.0 on conda-forge, making me sad. I will probably try again tomorrow or Monday.

**Comment by ZLLentz** [comment]
Actually, the v2.9.0 for pytmc didn't actually run... some weird CI error

**Comment by ZLLentz** [comment]
I'm going to push out an environment that holds back pytmc and pydm for the various build errors we've been seeing. If it passes the CI I will deploy it tonight. If it does not pass the CI I will hold off until next week.

**Comment by ZLLentz** [comment]
Nothing failed in the tests per se, but the build log is flooded with 50,000+ lines of the following at the teardown of the `pcdsdevices` tests:
```
Traceback (most recent call last):
  File "/home/travis/build/pcdshub/pcds-envs/miniconda/envs/pcds-test/lib/python3.8/weakref.py", line 642, in _exitfunc
    f()
  File "/home/travis/build/pcdshub/pcds-envs/miniconda/envs/pcds-test/lib/python3.8/weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/travis/build/pcdshub/pcds-envs/miniconda/envs/pcds-test/lib/python3.8/site-packages/ophyd/signal.py", line 813, in finalize
    cl.release_pvs(read_pv)
  File "/home/travis/build/pcdshub/pcds-envs/miniconda/envs/pcds-test/lib/python3.8/site-packages/ophyd/_pyepics_shim.py", line 125, in release_pvs
    epics.ca.clear_channel(pv.chid)
AttributeError: module 'epics' has no attribute 'ca'
```
I declare a Friday

**Comment by ZLLentz** [comment]
At this point I'm going to go for a full clean tag with updated pytmc, pydm, typhos, timechart

**Comment by ZLLentz** [comment]
Currently the only failure is in the pip check:
```
sphinx-rtd-theme 0.5.2 has requirement docutils<0.17, but you have docutils 0.17
```
https://travis-ci.com/github/pcdshub/pcds-envs/jobs/496466562#L5146

**Comment by ZLLentz** [comment]
Going to wait for +1 transfocate update from @klauer, should be easy because we've already found all the build issues

**Comment by klauer** [comment]
I think transfocator v0.5.0 should be ready - and hope it doesn't cause further issues here...

**Comment by ZLLentz** [comment]
Still have the anaconda caching issue. Rather than fight it I'll run the script first thing tomorrow.

**Comment by klauer** [comment]
Looks like we're good to go finally 👏

**Comment by ZLLentz** [comment]
Yes! One last peek at the travis and then we'll ship this out.

**Comment by ZLLentz** [comment]
Not even a race condition, each test passed on the first try. Let's go

**Pull request merged**
